require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/NumericPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Naming/MethodParameterName:
  Enabled: true
  MinNameLength: 2

Metrics/MethodLength:
  Enabled: true
  Max: 100

Metrics/BlockLength:
  Enabled: true
  Max: 100

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 100

RSpec/MultipleExpectations:
  Enabled: false
