test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: sg_tiny_backup_test

test_mysql:
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  database: sg_tiny_backup_test
